#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?
import math

for n in range(12000,20000):
    tri = int((n * (n +1)) / 2)
    divisors = 0
    for i in range (2, math.ceil(math.sqrt(tri)+1)):
            if tri % i == 0 and i * i == tri:
                divisors += 1
            elif tri % i == 0:
                divisors +=2
            else:
                continue
    if divisors >= 498:
        print(divisors)
        print("\nAnswer is " + str(tri) + " since it has " + str(divisors) + " divisors.")
        break
    else:
        print(divisors)